export const ALL_PRODUCTS_REQUEST = 'ALL PRODUCTS REQUEST';
export const ALL_PRODUCTS_SUCCESS = 'ALL PRODUCTS SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL PRODUCTS FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
